# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: minasyanakk
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0-b7c13d7"
  arc: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
