# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "den-vasyliev/kbot"
  tag: "v1.0.0-106879e"
  os: linux
  arch: amd64
  registry: "ghcr.io"
  TELE_TOKEN: TELE_TOKEN
replicaCount: 1
service:
  port: 80
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN
securityContext:
  privileged: true
